modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/CodeOfArdonia/SongsOfWar/issues"
[[mods]]
modId = "sow"
version = "${version}"
displayName = "Songs Of War"
logoFile = "logo_2.jpg"
authors = "IAFEnvoy, HF_ColdWind"
description = '''
The Songs of War Animation Mod
'''
[[dependencies.sow]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.sow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.sow]]
modId = "neptune"
mandatory = true
versionRange = "[1.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.sow]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
